// <auto-generated />
using System;
using DoggyRestApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoggyRestApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230831234512_Add_MoreFields_LineItem")]
    partial class Add_MoreFields_LineItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoggyRestApi.Models.LineItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int?>("DepartureCity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<double?>("DiscountPercent")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TouristRouteId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TravelDays")
                        .HasColumnType("int");

                    b.Property<int?>("TripType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("LineItem");
                });

            modelBuilder.Entity("DoggyRestApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderCreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionMetaData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DoggyRestApi.Models.OrderedItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double?>("DiscountPercent")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TouristRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TouristRouteId");

                    b.ToTable("OrderedItem");
                });

            modelBuilder.Entity("DoggyRestApi.Models.ProjectIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DoggyRestApi.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("shoppingCarts");
                });

            modelBuilder.Entity("DoggyRestApi.Models.TouristRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartureCity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<double?>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fees")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TravelDays")
                        .HasColumnType("int");

                    b.Property<int?>("TripType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TouristRoutes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e5e8533-9e02-40e7-b6f3-3ee549d64301"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Experience the beauty of Austria on this 5-day tour. Explore the historic city of Vienna and its magnificent palaces. Visit the charming town of Hallstatt and marvel at its picturesque landscapes. Discover the cultural treasures of Salzburg, birthplace of Mozart. Enjoy traditional Austrian cuisine and immerse yourself in the rich history and culture of this enchanting country.",
                            DiscountPercent = 0.20000000000000001,
                            Features = "Guided tours, Accommodation in boutique hotels, Transportation within Austria",
                            Fees = "Entrance fees to attractions, Meals not included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 9200.0m,
                            Rating = 4.0,
                            Title = "Austrian Discovery - Vienna, Hallstatt, Salzburg",
                            TravelDays = 5,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("7c9a105f-777e-4ed5-93c1-4d26c246d4c5"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Embark on an unforgettable 8-day adventure through Austria's scenic landscapes. Begin your journey in Vienna, known for its grand architecture and cultural heritage. Explore the Alpine region of Tyrol and experience the charm of Innsbruck. Discover the beauty of the Wachau Valley and enjoy wine tasting in the vineyards. Immerse yourself in Austrian traditions and create lasting memories on this remarkable tour.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Sightseeing tours, Accommodation in mountain resorts, Transportation within Austria",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 15600.0m,
                            Rating = 5.0,
                            Title = "Alpine Escape - Vienna, Tyrol, Innsbruck",
                            TravelDays = 8,
                            TripType = 3
                        },
                        new
                        {
                            Id = new Guid("5342e7fe-3b03-495f-9b4c-08fcfa1ea4fb"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Immerse yourself in the beauty of Austria's lakes and mountains on this 6-day tour. Explore the charming city of Salzburg and visit the iconic locations from the 'Sound of Music'. Experience the serenity of Lake Wolfgang and take a boat ride across its crystal-clear waters. Discover the stunning landscapes of the Austrian Alps and enjoy thrilling outdoor activities. Indulge in delicious Austrian cuisine and create lifelong memories on this unforgettable journey.",
                            DiscountPercent = 0.14999999999999999,
                            Features = "Guided tours, Accommodation in lakeside hotels, Transportation within Austria",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 13200.0m,
                            Rating = 4.0,
                            Title = "Lakes and Mountains - Salzburg, Lake Wolfgang",
                            TravelDays = 6,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("a9e6e77e-f971-446b-9a23-09d23c722be2"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Discover the best of Austria in 9 unforgettable days. Begin your journey in Vienna and visit its iconic landmarks. Explore the beautiful city of Graz and admire its medieval architecture. Immerse yourself in the cultural heritage of Salzburg and enjoy the stunning views of the Salzkammergut region. Indulge in wine tasting in the Wachau Valley and experience the charm of Austria's countryside. This tour offers a perfect blend of history, culture, and natural beauty.",
                            DiscountPercent = 0.20000000000000001,
                            Features = "Sightseeing tours, Accommodation in 4-star hotels, Transportation within Austria",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 19500.0m,
                            Rating = 5.0,
                            Title = "Best of Austria - Vienna, Graz, Salzburg",
                            TravelDays = 9,
                            TripType = 4
                        },
                        new
                        {
                            Id = new Guid("e9561271-5fcd-498f-86f4-bd2598ea9ec8"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Experience the magic of the Austrian Alps on this 4-day winter adventure. Explore the world-renowned ski resorts of Innsbruck and enjoy thrilling winter sports activities. Discover the beauty of the Stubai Glacier and indulge in panoramic views of the surrounding mountains. Immerse yourself in Austrian hospitality and warm up with traditional alpine cuisine. This tour is perfect for snow enthusiasts and nature lovers alike.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Skiing and snowboarding, Accommodation in alpine lodges, Transportation within Austria",
                            Fees = "Ski pass, Equipment rental included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 8500.0m,
                            Rating = 4.0,
                            Title = "Alpine Winter Wonderland - Innsbruck, Stubai Glacier",
                            TravelDays = 4,
                            TripType = 1
                        },
                        new
                        {
                            Id = new Guid("22f6d1f4-ff26-429f-b7c2-bab8a6624e6f"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Embark on a culinary journey through Austria on this 7-day food and wine tour. Begin your adventure in Vienna and indulge in traditional Viennese cuisine. Explore the vineyards of the Wachau Valley and savor exquisite wines. Discover the culinary delights of Graz and enjoy a cooking class to learn the secrets of Austrian cuisine. Immerse yourself in the flavors of Austria and experience a gastronomic adventure like no other.",
                            DiscountPercent = 0.14999999999999999,
                            Features = "Food and wine tastings, Accommodation in gourmet hotels, Transportation within Austria",
                            Fees = "Meals included, Personal expenses not included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 14500.0m,
                            Rating = 5.0,
                            Title = "Taste of Austria - Vienna, Wachau Valley, Graz",
                            TravelDays = 7,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("d685b277-2e33-421f-9eab-26d7d8e6fe2e"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Experience the charm of Austria's Christmas markets on this 3-day festive tour. Visit the enchanting markets in Vienna and stroll through the beautifully decorated stalls. Immerse yourself in the magical atmosphere and taste traditional holiday treats. Explore the historic city of Salzburg and its famous Christmas market. Indulge in mulled wine and gingerbread cookies as you soak up the holiday spirit in Austria.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Christmas market visits, Accommodation in city center hotels, Transportation within Austria",
                            Fees = "Meals not included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 6200.0m,
                            Rating = 4.0,
                            Title = "Austrian Christmas Markets - Vienna, Salzburg",
                            TravelDays = 3,
                            TripType = 1
                        },
                        new
                        {
                            Id = new Guid("16e5d1ed-2e5a-4ce7-a8da-15bb2c2073c9"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Explore the natural wonders of Austria on this 10-day outdoor adventure. Hike through the picturesque landscapes of the Austrian Alps and enjoy breathtaking views. Visit the stunning lakes of the Salzkammergut region and take a refreshing swim in crystal-clear waters. Experience the thrill of white-water rafting in the Tirol region. Immerse yourself in the beauty of Austria's national parks and create lasting memories in the heart of nature.",
                            DiscountPercent = 0.20000000000000001,
                            Features = "Hiking and outdoor activities, Accommodation in mountain lodges, Transportation within Austria",
                            Fees = "Equipment rental included, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 17800.0m,
                            Rating = 5.0,
                            Title = "Outdoor Escapes - Austrian Alps, Salzkammergut",
                            TravelDays = 10,
                            TripType = 3
                        },
                        new
                        {
                            Id = new Guid("f08cdd81-7c88-4a12-9099-783b3af05f95"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Discover the hidden gems of Austria on this 6-day off-the-beaten-path tour. Explore the charming village of Hallstatt and its breathtaking lakeside scenery. Visit the historical city of Graz and wander through its cobblestone streets. Discover the fairy-tale landscapes of the Salzkammergut region and enjoy leisurely boat rides. Immerse yourself in the authentic Austrian culture and experience the true essence of this captivating country.",
                            DiscountPercent = 0.14999999999999999,
                            Features = "Guided tours, Accommodation in charming guesthouses, Transportation within Austria",
                            Fees = "Entrance fees to attractions, Meals not included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 13500.0m,
                            Rating = 4.0,
                            Title = "Hidden Austria - Hallstatt, Graz, Salzkammergut",
                            TravelDays = 6,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("21b8cbe0-05b7-43c5-941e-4a874e2b7bc0"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 1,
                            Description = "Experience the beauty of Austria's lakes and mountains on this 9-day scenic tour. Begin your journey in Vienna and explore its architectural wonders. Visit the charming town of Zell am See and enjoy panoramic views of Lake Zell and the surrounding Alps. Discover the beauty of the Grossglockner High Alpine Road and hike through pristine alpine landscapes. Immerse yourself in Austrian culture and indulge in delicious local cuisine.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Sightseeing tours, Accommodation in lakeside resorts, Transportation within Austria",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 16800.0m,
                            Rating = 5.0,
                            Title = "Lakes and Mountains Discovery - Vienna, Zell am See",
                            TravelDays = 9,
                            TripType = 3
                        },
                        new
                        {
                            Id = new Guid("a12d92a5-4fc6-4d0d-bc94-6f30762c0a52"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Discover the wonders of New Zealand on this 7-day adventure. Begin your journey in Auckland and explore its vibrant cityscape. Visit the geothermal wonders of Rotorua and immerse yourself in Maori culture. Journey through the stunning landscapes of the South Island and witness the beauty of Milford Sound. Experience thrilling activities such as bungee jumping and skydiving in Queenstown. This tour offers an unforgettable exploration of New Zealand's natural wonders.",
                            DiscountPercent = 0.14999999999999999,
                            Features = "Sightseeing tours, Accommodation in 4-star hotels, Transportation between cities",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 14500.0m,
                            Rating = 4.0,
                            Title = "New Zealand Explorer - Auckland, Rotorua, Queenstown",
                            TravelDays = 7,
                            TripType = 3
                        },
                        new
                        {
                            Id = new Guid("76870d56-35a9-4b26-84da-f36d2d1b6d5c"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Embark on a 10-day adventure through the stunning landscapes of New Zealand. Begin your journey in Auckland and explore its iconic landmarks. Visit the cultural hub of Wellington and discover its vibrant arts scene. Journey through the breathtaking landscapes of the South Island and marvel at the beauty of Fiordland National Park. Immerse yourself in New Zealand's natural wonders and create lifelong memories on this unforgettable tour.",
                            DiscountPercent = 0.20000000000000001,
                            Features = "Guided tours, Accommodation in luxury resorts, Domestic flights within New Zealand",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 17800.0m,
                            Rating = 5.0,
                            Title = "New Zealand Highlights - Auckland, Wellington, South Island",
                            TravelDays = 10,
                            TripType = 4
                        },
                        new
                        {
                            Id = new Guid("e0f319a1-0f20-45e0-938f-527ac77dddb5"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Experience the beauty of New Zealand's North Island on this 6-day cultural tour. Begin your journey in Auckland and discover its Maori heritage. Visit the thermal wonderland of Rotorua and learn about traditional Maori arts and crafts. Explore the stunning landscapes of the Bay of Islands and cruise through its pristine waters. Immerse yourself in the rich Maori culture and create lasting memories on this immersive cultural adventure.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Cultural experiences, Accommodation in Maori-inspired lodges, Transportation within New Zealand",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 13200.0m,
                            Rating = 4.0,
                            Title = "Maori Discovery - Auckland, Rotorua, Bay of Islands",
                            TravelDays = 6,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("3010192b-0035-4ef7-8bc5-b81d5dc103a0"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Embark on an unforgettable 8-day journey through the breathtaking landscapes of the South Island of New Zealand. Begin your adventure in Christchurch and explore its vibrant art scene. Visit the stunning Lake Tekapo and witness its turquoise waters. Journey through the majestic Southern Alps and marvel at the beauty of Aoraki/Mount Cook. Experience the thrill of glacier hiking in Franz Josef and explore the pristine fjords of Milford Sound. This tour offers a perfect blend of adventure and natural beauty.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Sightseeing tours, Accommodation in wilderness lodges, Transportation within New Zealand",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 15600.0m,
                            Rating = 5.0,
                            Title = "South Island Expedition - Christchurch, Franz Josef, Milford Sound",
                            TravelDays = 8,
                            TripType = 3
                        },
                        new
                        {
                            Id = new Guid("f3821f4a-86b2-4d02-aefb-9e53f86b1dc0"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Discover the natural wonders of New Zealand on this 9-day outdoor adventure. Explore the rugged landscapes of the North Island and witness the power of geothermal activity in Rotorua. Journey to the South Island and hike through the breathtaking Southern Alps. Experience the thrill of bungee jumping in Queenstown and kayak in the pristine waters of Abel Tasman National Park. Immerse yourself in the beauty of New Zealand's nature and create lifelong memories on this adrenaline-filled tour.",
                            DiscountPercent = 0.20000000000000001,
                            Features = "Outdoor activities, Accommodation in adventure lodges, Transportation within New Zealand",
                            Fees = "Equipment rental included, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 19500.0m,
                            Rating = 5.0,
                            Title = "Outdoor Thrills - Rotorua, Queenstown, Abel Tasman",
                            TravelDays = 9,
                            TripType = 3
                        },
                        new
                        {
                            Id = new Guid("ae079869-6b29-4987-a34f-6814a4b47b3d"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Embark on a 5-day journey through the stunning landscapes of the North Island of New Zealand. Begin your adventure in Wellington and discover the capital city's cultural attractions. Visit the geothermal wonderland of Rotorua and experience the thrill of Maori performances. Explore the picturesque town of Taupo and witness the beauty of Huka Falls. Immerse yourself in New Zealand's natural wonders and create lasting memories on this compact yet unforgettable tour.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Sightseeing tours, Accommodation in city center hotels, Transportation within New Zealand",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 9600.0m,
                            Rating = 4.0,
                            Title = "North Island Discovery - Wellington, Rotorua, Taupo",
                            TravelDays = 5,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("4d65c663-8e08-4b48-8e94-8b5a5ac62eaa"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Experience the best of New Zealand's wine regions on this 7-day tour. Visit the renowned wineries of Marlborough and taste exquisite Sauvignon Blanc. Explore the picturesque vineyards of Hawke's Bay and indulge in award-winning wines. Immerse yourself in the art of winemaking and learn from expert vintners. This tour offers a perfect blend of wine tasting, gourmet cuisine, and breathtaking landscapes.",
                            DiscountPercent = 0.14999999999999999,
                            Features = "Wine tastings, Accommodation in vineyard estates, Transportation within New Zealand",
                            Fees = "Wine tasting fees included, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 13200.0m,
                            Rating = 5.0,
                            Title = "Wine Lover's Delight - Marlborough, Hawke's Bay",
                            TravelDays = 7,
                            TripType = 2
                        },
                        new
                        {
                            Id = new Guid("5f0a9de3-3a5f-41e7-ae03-57d24b925b45"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Embark on a 12-day grand tour of New Zealand and experience the country's diverse landscapes and cultural heritage. Journey from the North Island to the South Island, visiting iconic destinations such as Auckland, Rotorua, Wellington, Christchurch, Queenstown, and more. Immerse yourself in Maori culture, explore stunning national parks, and indulge in thrilling adventure activities. This comprehensive tour offers a complete New Zealand experience.",
                            DiscountPercent = 0.20000000000000001,
                            Features = "Comprehensive guided tour, Accommodation in premium hotels, Domestic flights within New Zealand",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 21500.0m,
                            Rating = 5.0,
                            Title = "Grand New Zealand Adventure - North Island, South Island",
                            TravelDays = 12,
                            TripType = 4
                        },
                        new
                        {
                            Id = new Guid("8878af46-5bb1-4d19-9a8d-3d0b4f091bcf"),
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = 2,
                            Description = "Explore the stunning landscapes of New Zealand's South Island on this 8-day adventure. Begin your journey in Christchurch and discover its vibrant arts scene. Visit the majestic Aoraki/Mount Cook and witness its snow-capped peaks. Journey through the breathtaking Fiordland National Park and cruise through the iconic Milford Sound. Immerse yourself in the natural beauty of New Zealand and experience a true outdoor adventure.",
                            DiscountPercent = 0.10000000000000001,
                            Features = "Sightseeing tours, Accommodation in wilderness lodges, Transportation within New Zealand",
                            Fees = "Entrance fees to attractions, Meals included",
                            Notes = "Airfare not included, Valid passport required",
                            OriginalPrice = 16800.0m,
                            Rating = 4.0,
                            Title = "South Island Discovery - Christchurch, Mount Cook, Milford Sound",
                            TravelDays = 8,
                            TripType = 3
                        });
                });

            modelBuilder.Entity("DoggyRestApi.Models.TouristRoutePicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("TouristRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TouristRouteId");

                    b.ToTable("TouristRoutePictures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TouristRouteId = new Guid("6e5e8533-9e02-40e7-b6f3-3ee549d64301"),
                            Url = "Sydney_12345.jpg"
                        },
                        new
                        {
                            Id = 2,
                            TouristRouteId = new Guid("6e5e8533-9e02-40e7-b6f3-3ee549d64301"),
                            Url = "Melbourne_67890.jpg"
                        },
                        new
                        {
                            Id = 3,
                            TouristRouteId = new Guid("6e5e8533-9e02-40e7-b6f3-3ee549d64301"),
                            Url = "Brisbane_23456.jpg"
                        },
                        new
                        {
                            Id = 4,
                            TouristRouteId = new Guid("7c9a105f-777e-4ed5-93c1-4d26c246d4c5"),
                            Url = "Perth_34567.jpg"
                        },
                        new
                        {
                            Id = 5,
                            TouristRouteId = new Guid("7c9a105f-777e-4ed5-93c1-4d26c246d4c5"),
                            Url = "Adelaide_78901.jpg"
                        },
                        new
                        {
                            Id = 6,
                            TouristRouteId = new Guid("7c9a105f-777e-4ed5-93c1-4d26c246d4c5"),
                            Url = "Auckland_45678.jpg"
                        },
                        new
                        {
                            Id = 7,
                            TouristRouteId = new Guid("5342e7fe-3b03-495f-9b4c-08fcfa1ea4fb"),
                            Url = "Wellington_90123.jpg"
                        },
                        new
                        {
                            Id = 8,
                            TouristRouteId = new Guid("5342e7fe-3b03-495f-9b4c-08fcfa1ea4fb"),
                            Url = "Christchurch_56789.jpg"
                        },
                        new
                        {
                            Id = 9,
                            TouristRouteId = new Guid("5342e7fe-3b03-495f-9b4c-08fcfa1ea4fb"),
                            Url = "GoldCoast_23456.jpg"
                        },
                        new
                        {
                            Id = 10,
                            TouristRouteId = new Guid("5342e7fe-3b03-495f-9b4c-08fcfa1ea4fb"),
                            Url = "Cairns_78901.jpg"
                        },
                        new
                        {
                            Id = 11,
                            TouristRouteId = new Guid("5342e7fe-3b03-495f-9b4c-08fcfa1ea4fb"),
                            Url = "Queenstown_34567.jpg"
                        },
                        new
                        {
                            Id = 12,
                            TouristRouteId = new Guid("a9e6e77e-f971-446b-9a23-09d23c722be2"),
                            Url = "Rotorua_89012.jpg"
                        },
                        new
                        {
                            Id = 13,
                            TouristRouteId = new Guid("a9e6e77e-f971-446b-9a23-09d23c722be2"),
                            Url = "SydneyOperaHouse_56789.jpg"
                        },
                        new
                        {
                            Id = 14,
                            TouristRouteId = new Guid("a9e6e77e-f971-446b-9a23-09d23c722be2"),
                            Url = "GreatBarrierReef_23456.jpg"
                        },
                        new
                        {
                            Id = 15,
                            TouristRouteId = new Guid("e9561271-5fcd-498f-86f4-bd2598ea9ec8"),
                            Url = "AyersRock_78901.jpg"
                        },
                        new
                        {
                            Id = 16,
                            TouristRouteId = new Guid("e9561271-5fcd-498f-86f4-bd2598ea9ec8"),
                            Url = "SydneyHarbourBridge_89012.jpg"
                        },
                        new
                        {
                            Id = 17,
                            TouristRouteId = new Guid("22f6d1f4-ff26-429f-b7c2-bab8a6624e6f"),
                            Url = "Hamilton_45678.jpg"
                        },
                        new
                        {
                            Id = 18,
                            TouristRouteId = new Guid("22f6d1f4-ff26-429f-b7c2-bab8a6624e6f"),
                            Url = "Dunedin_12345.jpg"
                        },
                        new
                        {
                            Id = 19,
                            TouristRouteId = new Guid("22f6d1f4-ff26-429f-b7c2-bab8a6624e6f"),
                            Url = "MelbourneMuseum_67890.jpg"
                        },
                        new
                        {
                            Id = 20,
                            TouristRouteId = new Guid("22f6d1f4-ff26-429f-b7c2-bab8a6624e6f"),
                            Url = "BlueMountains_23456.jpg"
                        },
                        new
                        {
                            Id = 21,
                            TouristRouteId = new Guid("d685b277-2e33-421f-9eab-26d7d8e6fe2e"),
                            Url = "SurfersParadise_78901.jpg"
                        },
                        new
                        {
                            Id = 22,
                            TouristRouteId = new Guid("d685b277-2e33-421f-9eab-26d7d8e6fe2e"),
                            Url = "AucklandSkyTower_56789.jpg"
                        },
                        new
                        {
                            Id = 23,
                            TouristRouteId = new Guid("d685b277-2e33-421f-9eab-26d7d8e6fe2e"),
                            Url = "QueenstownGardens_23456.jpg"
                        },
                        new
                        {
                            Id = 24,
                            TouristRouteId = new Guid("d685b277-2e33-421f-9eab-26d7d8e6fe2e"),
                            Url = "GreatOceanRoad_78901.jpg"
                        },
                        new
                        {
                            Id = 25,
                            TouristRouteId = new Guid("16e5d1ed-2e5a-4ce7-a8da-15bb2c2073c9"),
                            Url = "WellingtonBotanicGarden_89012.jpg"
                        },
                        new
                        {
                            Id = 26,
                            TouristRouteId = new Guid("16e5d1ed-2e5a-4ce7-a8da-15bb2c2073c9"),
                            Url = "SydneyHarbour_45678.jpg"
                        },
                        new
                        {
                            Id = 27,
                            TouristRouteId = new Guid("f08cdd81-7c88-4a12-9099-783b3af05f95"),
                            Url = "BondiBeach_12345.jpg"
                        },
                        new
                        {
                            Id = 28,
                            TouristRouteId = new Guid("f08cdd81-7c88-4a12-9099-783b3af05f95"),
                            Url = "BrisbaneCityHall_67890.jpg"
                        },
                        new
                        {
                            Id = 29,
                            TouristRouteId = new Guid("f08cdd81-7c88-4a12-9099-783b3af05f95"),
                            Url = "MelbourneZoo_23456.jpg"
                        },
                        new
                        {
                            Id = 30,
                            TouristRouteId = new Guid("21b8cbe0-05b7-43c5-941e-4a874e2b7bc0"),
                            Url = "MilfordSound_78901.jpg"
                        },
                        new
                        {
                            Id = 31,
                            TouristRouteId = new Guid("21b8cbe0-05b7-43c5-941e-4a874e2b7bc0"),
                            Url = "FranzJosefGlacier_89012.jpg"
                        },
                        new
                        {
                            Id = 32,
                            TouristRouteId = new Guid("a12d92a5-4fc6-4d0d-bc94-6f30762c0a52"),
                            Url = "AdelaideBotanicGarden_56789.jpg"
                        },
                        new
                        {
                            Id = 33,
                            TouristRouteId = new Guid("a12d92a5-4fc6-4d0d-bc94-6f30762c0a52"),
                            Url = "UluruKataTjutaNationalPark_23456.jpg"
                        },
                        new
                        {
                            Id = 34,
                            TouristRouteId = new Guid("76870d56-35a9-4b26-84da-f36d2d1b6d5c"),
                            Url = "KangarooIsland_78901.jpg"
                        },
                        new
                        {
                            Id = 35,
                            TouristRouteId = new Guid("76870d56-35a9-4b26-84da-f36d2d1b6d5c"),
                            Url = "AucklandWarMemorialMuseum_56789.jpg"
                        },
                        new
                        {
                            Id = 36,
                            TouristRouteId = new Guid("76870d56-35a9-4b26-84da-f36d2d1b6d5c"),
                            Url = "TePapaMuseum_23456.jpg"
                        },
                        new
                        {
                            Id = 37,
                            TouristRouteId = new Guid("e0f319a1-0f20-45e0-938f-527ac77dddb5"),
                            Url = "YarraRiver_78901.jpg"
                        },
                        new
                        {
                            Id = 38,
                            TouristRouteId = new Guid("e0f319a1-0f20-45e0-938f-527ac77dddb5"),
                            Url = "GreatBarrierReefMarinePark_89012.jpg"
                        },
                        new
                        {
                            Id = 39,
                            TouristRouteId = new Guid("e0f319a1-0f20-45e0-938f-527ac77dddb5"),
                            Url = "SydneyTowerEye_45678.jpg"
                        },
                        new
                        {
                            Id = 40,
                            TouristRouteId = new Guid("3010192b-0035-4ef7-8bc5-b81d5dc103a0"),
                            Url = "QueenVictoriaMarket_12345.jpg"
                        },
                        new
                        {
                            Id = 41,
                            TouristRouteId = new Guid("3010192b-0035-4ef7-8bc5-b81d5dc103a0"),
                            Url = "SydneyFishMarket_67890.jpg"
                        },
                        new
                        {
                            Id = 42,
                            TouristRouteId = new Guid("3010192b-0035-4ef7-8bc5-b81d5dc103a0"),
                            Url = "HobbitonMovieSet_23456.jpg"
                        },
                        new
                        {
                            Id = 43,
                            TouristRouteId = new Guid("f3821f4a-86b2-4d02-aefb-9e53f86b1dc0"),
                            Url = "SydneyRoyalBotanicGarden_78901.jpg"
                        },
                        new
                        {
                            Id = 44,
                            TouristRouteId = new Guid("f3821f4a-86b2-4d02-aefb-9e53f86b1dc0"),
                            Url = "MelbourneRoyalBotanicGardens_45678.jpg"
                        },
                        new
                        {
                            Id = 45,
                            TouristRouteId = new Guid("f3821f4a-86b2-4d02-aefb-9e53f86b1dc0"),
                            Url = "SydneyCove_12345.jpg"
                        },
                        new
                        {
                            Id = 46,
                            TouristRouteId = new Guid("ae079869-6b29-4987-a34f-6814a4b47b3d"),
                            Url = "MountCook_67890.jpg"
                        },
                        new
                        {
                            Id = 47,
                            TouristRouteId = new Guid("ae079869-6b29-4987-a34f-6814a4b47b3d"),
                            Url = "SydneyAquarium_23456.jpg"
                        },
                        new
                        {
                            Id = 48,
                            TouristRouteId = new Guid("4d65c663-8e08-4b48-8e94-8b5a5ac62eaa"),
                            Url = "WellingtonWaterfront_78901.jpg"
                        },
                        new
                        {
                            Id = 49,
                            TouristRouteId = new Guid("4d65c663-8e08-4b48-8e94-8b5a5ac62eaa"),
                            Url = "ChristchurchBotanicGardens_89012.jpg"
                        },
                        new
                        {
                            Id = 50,
                            TouristRouteId = new Guid("5f0a9de3-3a5f-41e7-ae03-57d24b925b45"),
                            Url = "GreatBarrierReefDiving_56789.jpg"
                        },
                        new
                        {
                            Id = 51,
                            TouristRouteId = new Guid("5f0a9de3-3a5f-41e7-ae03-57d24b925b45"),
                            Url = "LakeTaupo_23456.jpg"
                        },
                        new
                        {
                            Id = 52,
                            TouristRouteId = new Guid("8878af46-5bb1-4d19-9a8d-3d0b4f091bcf"),
                            Url = "FoxGlacier_78901.jpg"
                        },
                        new
                        {
                            Id = 53,
                            TouristRouteId = new Guid("8878af46-5bb1-4d19-9a8d-3d0b4f091bcf"),
                            Url = "SydneyOperaHouseAtNight_89012.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectIdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectIdentityUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectIdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("ProjectIdentityUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectIdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("ProjectIdentityUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectIdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("ProjectIdentityUserId");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoggyRestApi.Models.LineItem", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("LineItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("DoggyRestApi.Models.Order", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", "Owner")
                        .WithMany("Orders")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DoggyRestApi.Models.OrderedItem", b =>
                {
                    b.HasOne("DoggyRestApi.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoggyRestApi.Models.TouristRoute", "TouristRoute")
                        .WithMany()
                        .HasForeignKey("TouristRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TouristRoute");
                });

            modelBuilder.Entity("DoggyRestApi.Models.ShoppingCart", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", "Owner")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("DoggyRestApi.Models.ShoppingCart", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DoggyRestApi.Models.TouristRoutePicture", b =>
                {
                    b.HasOne("DoggyRestApi.Models.TouristRoute", "TouristRoute")
                        .WithMany("TouristRoutePictures")
                        .HasForeignKey("TouristRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TouristRoute");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("ProjectIdentityUserId");

                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("ProjectIdentityUserId");

                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("ProjectIdentityUserId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany("Tokens")
                        .HasForeignKey("ProjectIdentityUserId");

                    b.HasOne("DoggyRestApi.Models.ProjectIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoggyRestApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DoggyRestApi.Models.ProjectIdentityUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Orders");

                    b.Navigation("ShoppingCart")
                        .IsRequired();

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DoggyRestApi.Models.ShoppingCart", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("DoggyRestApi.Models.TouristRoute", b =>
                {
                    b.Navigation("TouristRoutePictures");
                });
#pragma warning restore 612, 618
        }
    }
}
